#!/usr/bin/env node
// Build the whitelist Merkle root + per-address proofs from a plain address list.
//
// Leaf  = keccak256(abi.encodePacked(address))           (matches WordRegistry.verifyWhitelist)
// Pair  = keccak256(sorted(left, right))                  (matches OZ MerkleProof.verify)
//
// Usage:
//   node merkle.mjs [addressFile] [outFile]
//   addressFile default: whitelist.example.txt
//   outFile     default: ../../shared/whitelist/proofs.json
//
// Writes { root, proofs: { "0xloweraddr": { proof: [...] } } } and prints the root to stdout
// (the deploy script reads the root from the proofs file).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { keccak256, encodePacked, concatHex, isAddress, getAddress } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const addressFile = resolve(here, process.argv[2] ?? "whitelist.example.txt");
const outFile = resolve(here, process.argv[3] ?? "../../shared/whitelist/proofs.json");

const addresses = readFileSync(addressFile, "utf8")
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith("#"));

if (addresses.length === 0) {
  console.error(`No addresses found in ${addressFile}`);
  process.exit(1);
}
for (const a of addresses) {
  if (!isAddress(a)) {
    console.error(`Invalid address: ${a}`);
    process.exit(1);
  }
}

const leafOf = (addr) => keccak256(encodePacked(["address"], [getAddress(addr)]));
const hashPair = (a, b) => (BigInt(a) <= BigInt(b) ? keccak256(concatHex([a, b])) : keccak256(concatHex([b, a])));

const leaves = addresses.map(leafOf);

function nextLevel(level) {
  const out = [];
  for (let i = 0; i < level.length; i += 2) {
    out.push(i + 1 < level.length ? hashPair(level[i], level[i + 1]) : level[i]); // odd node carries up
  }
  return out;
}

function computeRoot(leaves) {
  let level = leaves;
  while (level.length > 1) level = nextLevel(level);
  return level[0];
}

function proofFor(index) {
  const proof = [];
  let level = leaves;
  let idx = index;
  while (level.length > 1) {
    const sib = idx ^ 1;
    if (sib < level.length) proof.push(level[sib]);
    level = nextLevel(level);
    idx = Math.floor(idx / 2);
  }
  return proof;
}

const root = computeRoot(leaves);
const proofs = {};
addresses.forEach((addr, i) => {
  proofs[addr.toLowerCase()] = { proof: proofFor(i) };
});

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  JSON.stringify(
    {
      _comment:
        "Generated by contracts/tools/merkle.mjs. Maps lowercased address -> { proof }. Address list is a HUMAN TASK.",
      root,
      proofs,
    },
    null,
    2,
  ) + "\n",
);

console.error(`Wrote ${Object.keys(proofs).length} proofs to ${outFile}`);
console.log(root); // stdout = root only, so `ROOT=$(node merkle.mjs)` works
