#!/usr/bin/env node
// Wire a deployment's on-chain addresses into the indexer + web config, so deploy is mechanical.
// Reads shared/deployments/<network>.json (written by contracts/script/Deploy.s.sol) and:
//   - patches indexer/wrangler.toml [vars] REGISTRY / MARKETPLACE / START_BLOCK
//   - writes web/.env.production with the contract addresses (+ optional VITE_API_URL)
//
// Usage:
//   node scripts/wire-deploy.mjs [network=baseSepolia] [--rpc <url>] [--api <workerUrl>]
//
// Everything that needs YOUR Cloudflare account (D1 id, R2, ADMIN_TOKEN secret, the actual
// `wrangler deploy`) is printed as the remaining checklist — see DEPLOY.md.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const network = args.find((a) => !a.startsWith("--")) ?? "baseSepolia";
const flag = (name) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};
const rpc = flag("rpc");
const api = flag("api");

const depPath = resolve(root, `shared/deployments/${network}.json`);
if (!existsSync(depPath)) {
  console.error(`No deployment at ${depPath}. Deploy the contracts first (see DEPLOY.md step 1).`);
  process.exit(1);
}
const dep = JSON.parse(readFileSync(depPath, "utf8"));
const { wordRegistry, deedMarketplace, startBlock } = dep;
if (!wordRegistry || !deedMarketplace) {
  console.error("Deployment file is missing wordRegistry/deedMarketplace.");
  process.exit(1);
}

// 1) Patch indexer/wrangler.toml [vars]
const tomlPath = resolve(root, "indexer/wrangler.toml");
let toml = readFileSync(tomlPath, "utf8");
const setVar = (key, value) => {
  const re = new RegExp(`(^${key}\\s*=\\s*")[^"]*(")`, "m");
  if (re.test(toml)) toml = toml.replace(re, `$1${value}$2`);
  else console.warn(`  (couldn't find ${key} in wrangler.toml — set it manually)`);
};
setVar("REGISTRY", wordRegistry);
setVar("MARKETPLACE", deedMarketplace);
setVar("START_BLOCK", String(startBlock ?? 0));
if (rpc) setVar("RPC_URL", rpc);
writeFileSync(tomlPath, toml);
console.log(`✓ indexer/wrangler.toml: REGISTRY/MARKETPLACE/START_BLOCK${rpc ? "/RPC_URL" : ""} set`);

// 2) Write web/.env.production
const envPath = resolve(root, "web/.env.production");
const env = [
  `# Generated by scripts/wire-deploy.mjs for network=${network}. Build-time vars for the SPA.`,
  `VITE_WORD_REGISTRY=${wordRegistry}`,
  `VITE_DEED_MARKETPLACE=${deedMarketplace}`,
  api ? `VITE_API_URL=${api}` : `# VITE_API_URL=https://wordsmash-indexer.<your-subdomain>.workers.dev  # set after the Worker deploy`,
  `# VITE_WALLETCONNECT_PROJECT_ID=   # optional (HUMAN TASK)`,
  "", // VITE_USE_ANVIL intentionally unset -> Base Sepolia
].join("\n");
writeFileSync(envPath, env + "\n");
console.log(`✓ web/.env.production written`);

console.log(`\nRemaining (your Cloudflare account — see DEPLOY.md):`);
console.log(`  • RPC_URL${rpc ? " ✓" : " — pass --rpc <BaseSepoliaRpc> or edit wrangler.toml"}`);
console.log(`  • D1: wrangler d1 create wordsmash  → paste id into wrangler.toml`);
console.log(`  • ADMIN_TOKEN: wrangler secret put ADMIN_TOKEN`);
console.log(`  • PUBLIC_BASE + WEB_APP_BASE: set to the Worker + Pages URLs`);
console.log(`  • VITE_API_URL: ${api ? "✓" : "set to the Worker URL after deploy"}`);
